#!/usr/bin/env php
<?php
// the first line is necessary if we don't use the extension ".php"!
// this file load our cli capabilities and is exposed to
// allow advanced users to integrate own commands (based on symfony console)

use Neoan\Cli\Application;
use Neoan\NeoanApp;


require_once 'vendor/autoload.php';

$setup = (new \Neoan\Helper\Setup())->setLibraryPath(__DIR__ . '/src')->setPublicPath(__DIR__);


$app = new NeoanApp($setup , __DIR__);
new \Config\Bootstrap($app);
$console = new Application($app);
$console->run();