#!/usr/bin/env php
<?php
// the first line is necessary if we don't use the extension ".php"!
// this file load our cli capabilities and is exposed to
// allow advanced users to integrate own commands (based on symfony console)

use Commands\CreateJWTForUser;
use Commands\CreateTypescriptInterface;
use Commands\CreateUserCommand;
use Commands\CreateUUID;
use Commands\GetUuid;
use Commands\ScaffoldModel;
use Commands\ScaffoldPermission;
use Commands\ScaffoldRequest;
use Commands\ScaffoldRoute;
use Commands\UpdatePassword;
use Neoan\Cli\Application;
use Neoan\NeoanApp;


require_once 'vendor/autoload.php';

$setup = (new \Neoan\Helper\Setup())->setLibraryPath(__DIR__ . '/src')->setPublicPath(__DIR__);


$app = new NeoanApp($setup , __DIR__);
new \Config\Bootstrap($app);
$console = new Application($app);
$console->add(new CreateUserCommand());
$console->add(new CreateJWTForUser());
$console->add(new CreateUUID());
$console->add(new GetUuid());
$console->add(new UpdatePassword());
$console->add(new CreateTypescriptInterface());
$console->add(new ScaffoldPermission($app));
$console->add(new ScaffoldRequest($app));
$console->add(new ScaffoldRoute($app));
$console->add(new ScaffoldModel($app));
$console->run();